name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Upload tests as artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: |
            build/test-results
            build/reports

      - name: Create test report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Junit Tests
          path: build/test-results/**/*.xml
          reporter: java-junit

